perf(proxy): Improve compression performance
edgee-cloud/edgee pull request #103
Opened 2024-10-17 15:17 UTC by KokaKiwi

### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

- Defer response compression to `tower-http`
  * Also remove the `Accept-Encoding` header passed to the endpoint since we don't need compression between the proxy and endpoint, we only need to comply to this header to the client.
- Add base for tower-based request handling

### Related Issues

- #40

2024-10-22 06:24 UTC, SachaMorard requested changes
Your PR seems very interesting, but I'd keep the decompression process as it is, or at least make it optional. In some cases, the user might want to keep compressed exchanges between the backend and Edgee to reduce bandwidth costs...

This PR is quite important, and in this case, I recommend not “polluting” it with refacto lines, as this makes it easier to read.

2024-10-22 06:24 UTC, SachaMorard commented on src/config/config.rs
> -    pub max_compressed_body_size: usize,
@KokaKiwi why removing this configuration line?
It is important for the computation process and is not linked to the response compression.

2024-10-22 06:24 UTC, SachaMorard commented on src/proxy/context/proxy.rs
> +        incoming_headers.remove("accept-encoding");
I would prefer to make this optional. 
Because in some cases, it could have a huge impact on the bandwidth cost of the user

2024-10-22 06:24 UTC, SachaMorard commented on src/proxy/controller/controller.rs
> +    parts.headers.remove("transfer-encoding");
Why remove this response header?

2024-10-22 09:19 UTC, KokaKiwi commented on src/proxy/controller/controller.rs
> +    parts.headers.remove("transfer-encoding");
It was a header i removed during dev because i'm using `miniserve` to serve the demo-html with compression and it was adding this header with value `chunked` which conflicted with other `content-length` (as per [the specs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding#chunked)) and `hyper` would then throw an error.
I wanted to investigate more this "corner case" before actually committing a fix (if needed) and i forgot to remove this temporary line when creating the PR

2024-10-30 08:18 UTC, SachaMorard requested changes

2024-10-30 08:18 UTC, SachaMorard commented on src/config/config.rs
> +    pub compress: bool,
👍

2024-10-30 08:18 UTC, SachaMorard commented on src/proxy/proxy.rs
>              match do_only_proxy(request.get_method(), &response_body, &response) {
`do_only_proxy` is now happening after the decompression... 
I'm not sure about its side effects. 
For example, if the backend serves a CSS resource, we don't need to decompress the response at all; we can simply serve it as is. With this implementation, we decompress each backend response, right?

2024-10-30 08:19 UTC, SachaMorard commented
@KokaKiwi it's really good! 👏👏
I just have a concern about the decompression timing. Let's have a talk about it

2024-10-30 17:19 UTC, KokaKiwi commented
> @KokaKiwi it's really good! 👏👏 I just have a concern about the decompression timing. Let's have a talk about it

It was not a trivial fix but now it should decompress the body only when needed, also the fix made the code a bit cleaner with the addition of `ProxyBody` :)

2024-10-31 05:14 UTC, SachaMorard approved these changes

2024-10-31 08:37 UTC, merged