Update dev.up Make Command
edgee-cloud/edgee pull request #158
Opened 2024-12-24 09:18 UTC by Jer1605

### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

This PR introduces a fix for the `Make dev.up` command, so it runs correctly on linux adding the `serve` command.

### Related Issues
https://linear.app/edgee/issue/EDGEE-302/[edgee]-make-devup-command-should-work-on-linux

2024-12-26 14:57 UTC, SachaMorard requested changes
You added `package-lock.json` but I think it's an error, right?

2024-12-26 18:20 UTC, SachaMorard approved these changes

2025-01-06 13:14 UTC, SachaMorard requested changes
@Jer1605 you have to remove package-lock.json

2025-01-08 15:21 UTC, alexcasalboni approved these changes

2025-01-08 16:30 UTC, SachaMorard approved these changes

2025-01-08 19:15 UTC, merged