docs: update README - copyediting & typos
edgee-cloud/edgee pull request #24
Opened 2024-08-21 15:24 UTC by alexcasalboni

### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

A few messaging improvements and fixed a couple of typos.

### Related Issues

N/A

2024-08-21 15:35 UTC, SachaMorard requested changes
Hello @alexcasalboni 
Thank you very much for this first contribution ;)
I've detected a little typo that needs to be corrected.

2024-08-21 15:35 UTC, SachaMorard commented on README.md
> +The example above sets up one backend called "demo". As the default backend, it will recenved all traffic directed to `demo.edgee.dev`. Additionaly, projects can have a number of backends and use rou
Little typo "recenved"

2024-08-23 10:34 UTC, alexcasalboni commented on README.md
> +The example above sets up one backend called "demo". As the default backend, it will recenved all traffic directed to `demo.edgee.dev`. Additionaly, projects can have a number of backends and use rou
Fixed, thanks :)

2024-08-23 10:37 UTC, SachaMorard approved these changes

2024-08-23 10:37 UTC, merged