feat: enabled user to select either HTTP or HTTPS
edgee-cloud/edgee pull request #41
Opened 2024-09-05 10:20 UTC by spantheslayer

### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes
Changed the `entrypoint::start()` method to launch either `web::start()` and/or `websecure::start()`

### Related Issues
Either HTTP or HTTPS is mandatory, but not both #35

2024-09-05 13:45 UTC, SachaMorard commented
@spantheslayer I probably have to explain better the use case. 
Edgee user has to be able  to use HTTP entrypoint only
```toml
[log]
level = "info"

[http]
address = "0.0.0.0:80"
force_https = false

[[routing]]
domain = "demo.edgee.dev"

[[routing.backends]]
name = "demo"
default = true
address = "localhost:8080"
enable_ssl = true
```

But Edgee user has to be able to use HTTPS entrypoint only
```toml
[log]
level = "info"

[https]
address = "0.0.0.0:443"
cert = "certs/fullchain.pem"
key = "certs/privkey.pem"

[[routing]]
domain = "demo.edgee.dev"

[[routing.backends]]
name = "demo"
default = true
address = "localhost:8080"
enable_ssl = true
```

And, Edgee user has to be able to use both HTTP and HTTPS entrypoint
```toml
[log]
level = "info"

[http]
address = "0.0.0.0:80"
force_https = false

[https]
address = "0.0.0.0:443"
cert = "certs/fullchain.pem"
key = "certs/privkey.pem"

[[routing]]
domain = "demo.edgee.dev"

[[routing.backends]]
name = "demo"
default = true
address = "localhost:8080"
enable_ssl = true
```

I think you should consider modifying `StaticConfiguration.http` and `StaticConfiguration.https` types with an Option. Like:
```rust
pub struct StaticConfiguration {
    pub log: Option<LogConfiguration>,
    pub http: Option<HttpConfiguration>,
    pub https: Option<HttpsConfiguration>,
}
```

2024-09-05 13:45 UTC, SachaMorard requested changes

2024-09-05 13:45 UTC, SachaMorard commented on src/entrypoint.rs
> +    let enable_http = !config.http.force_https;
The behavior is not ok. When `force_https` is set to `true`, edgee has to listen to the http port and respond redirect responses to all http requests.
With this line, redirections do not happen anymore.

2024-09-09 16:30 UTC, spantheslayer commented
Hi @SachaMorard , made some changes as you pointed out, please check and lmk. thanks.

2024-09-10 03:45 UTC, SachaMorard requested changes

2024-09-10 03:45 UTC, SachaMorard commented on edgee.sample.toml
> -[log]
caution: this file must not be deleted

2024-09-10 03:45 UTC, SachaMorard commented on src/entrypoint.rs
> +    if !incoming_ctx.is_https && config::get().http.clone().unwrap().force_https {
```rust
if !incoming_ctx.is_https && config::get().http.is_some() && config::get().http.as_ref().unwrap().force_https {
```

2024-09-10 03:45 UTC, SachaMorard commented on src/tools/edgee_cookie.rs
> +        .secure(config::get().http.clone().unwrap().force_https)
to improve readability and efficiency, I'd write like this:

```rust
fn set_cookie(value: &str, res_headers: &mut http::HeaderMap, host: &str) {
    let secure = config::get().http.is_some() && config::get().http.as_ref().unwrap().force_https;
    let root_domain = get_root_domain(host);
    let cookie = Cookie::build((&config::get().security.cookie_name, value))
        .domain(root_domain)
        .path("/")
        .http_only(false)
        .secure(secure)
        .same_site(SameSite::Lax)
        .expires(OffsetDateTime::now_utc() + StdDuration::from_secs(365 * 24 * 60 * 60));
        
        res_headers.insert(SET_COOKIE, HeaderValue::from_str(cookie.to_string().as_str()).unwrap());
}

2024-09-10 03:45 UTC, SachaMorard commented on src/entrypoint/websecure.rs
> +    };
Good!
I would remove the commented line, and shorten your instruction:

```rust
let cfg = config::get().https.as_ref().ok_or_else(|| anyhow::anyhow!("HTTPS configuration is missing"))?;
```

2024-09-10 03:45 UTC, SachaMorard commented on src/entrypoint/web.rs
> +    };
Good!
I would remove the commented line, and shorten your instruction:

```rust
let cfg = config::get().http.as_ref().ok_or_else(|| anyhow::anyhow!("HTTP configuration is missing"))?;
```

2024-09-10 03:45 UTC, SachaMorard commented on src/entrypoint.rs
>  }
In addition to your code, I would keep the logic you developed earlier on the start() method:

```rust
pub async fn start() -> anyhow::Result<()> {
    let config =  config::get();
    let mut tasks = Vec::new();

    if config.http.is_some() {
        tasks.push(tokio::spawn(async {
            if let Err(err) = web::start().await {
                error!(?err, "Failed to start HTTP entrypoint");
            }
        }));
    }

    if config.https.is_some() {
        tasks.push(tokio::spawn(async {
            if let Err(err) = websecure::start().await {
                error!(?err, "Failed to start HTTPS entrypoint");
            }
        }));
    }

    tokio::select! {
        _ = tasks.pop().unwrap() => Ok(()),
    }
}
```

2024-09-10 04:44 UTC, SachaMorard requested changes

2024-09-10 04:44 UTC, SachaMorard commented on edgee.sample.toml
> -name = "amplitude"
Be careful, there are still some changes in that file ;)

2024-09-10 05:20 UTC, spantheslayer commented on edgee.sample.toml
> -name = "amplitude"
I believe you are referring about the wrong format of the file that happened because of an extension I had installed on my system.

2024-09-10 05:21 UTC, spantheslayer commented
This time I kept it ( the format ) as it is. I hope this is what is expected.

2024-09-10 05:23 UTC, SachaMorard requested changes

2024-09-10 05:23 UTC, SachaMorard commented on edgee.sample.toml
Sorry @spantheslayer but you changed the file rights. You really have to keep it like that

2024-09-10 05:27 UTC, spantheslayer commented on edgee.sample.toml
Ahh I see, Got it. Fixing that right away.

2024-09-10 06:24 UTC, SachaMorard approved these changes

2024-09-10 06:24 UTC, SachaMorard commented
All right @spantheslayer thank you ;)

2024-09-10 06:24 UTC, merged